### PR TITLE
Adding PowerShell Module Indented.Net.Dns

### PR DESCRIPTION
**Pull request by dalemorson**
- Adding the PowerShell module `Indented.Net.Dns`. This is a module that allows DNS resolution on both Windows and Linux using the cmdlet `Get-Dns`.
https://www.powershellgallery.com/packages/Indented.Net.Dns/6.1.1
https://github.com/indented-automation/Indented.Net.Dns
- The built-in cmdlet `Resolve-DnsName` does not work on Linux and therefore I needed a cmdlet that was compatible on both Windows and Linux. 
- This is in preparation for my `das-dns-automation-cleanup` solution that uses it to test whether a DNS record we've marked as `inactive` still resolves or not. 
- It needs to be available on the build agents so that when the Pester tests run it's available to mock. The script that will run at release will install if required.

### CODE REVIEW

**Comment by EwanNoble** [comment]
I'm not a fan of random modules like this, can we not use something like `[System.Net.Dns]::GetHostEntry($HostnameOrIP)` instead? https://stackoverflow.com/a/51423412

**Comment by EwanNoble** [comment]
Does this fit your use-case https://stackoverflow.com/a/51423412?

**Comment by dalemorson** [comment]
> Does this fit your use-case https://stackoverflow.com/a/51423412?

Unfortunately not as it only resolves A, AAAA, and PTR records. The `Get-Dns` cmdlet has a nice -RecordType parameter and I can pass in the record type from the JSON files.

**Comment by EwanNoble** [comment]
> > Does this fit your use-case https://stackoverflow.com/a/51423412?
> 
> Unfortunately not as it only resolves A, AAAA, and PTR records. The `Get-Dns` cmdlet has a nice -RecordType parameter and I can pass in the record type from the JSON files.

Have you tested it? I can resolve our own CNAME records with it, if all you're doing it "test whether a DNS record we've marked as inactive still resolves or not." then it should be enough?

**Comment by dalemorson** [comment]
> > > Does this fit your use-case https://stackoverflow.com/a/51423412?
> > 
> > 
> > Unfortunately not as it only resolves A, AAAA, and PTR records. The `Get-Dns` cmdlet has a nice -RecordType parameter and I can pass in the record type from the JSON files.
> 
> Have you tested it? I can resolve our own CNAME records with it, if all you're doing it "test whether a DNS record we've marked as inactive still resolves or not." then it should be enough?

Let me try it out 👍

**Comment by dalemorson** [comment]
Closing as `[System.Net.Dns]::GetHostEntry('')` can be used in replacement, and removes the dependency of an external module as it's built into PowerShell Core.

**Pull request closed without merging**
