### PR TITLE
Split powershell modules loading

### PR DESCRIPTION
**Pull request by mwevill**
Split module loading to ensure modules load before use.

### CODE REVIEW

**Comment by chelnak** [comment]
Why does the install need to be split @mwevill ?

**Comment by mwevill** [comment]
> Why does the install need to be split @mwevill ?

Issue with das-firewall tasks failing on the first run due to not being able to find Azure pester modules. This was a potential fix based on some internet research, Separate PR has enforced using powershell core for the associated task.  If this is not successful We can try this, Will not merge at the moment,

**Comment by chelnak** [comment]
Ok interesting one as this command accepts an array of module names to install. However installing a module does not import it in to the current runspace.

**Comment by jack-education** [comment]
Closing this and https://github.com/SkillsFundingAgency/das-azure-pipelines-agents/issues/40 as issue confirmed as resolved by requiring PowerShell Core for PowerShell task.

**Pull request closed without merging**
